# Generated by Django 5.2.5 on 2025-12-07 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_assessmentrecord_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Layer Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('layer_type', models.CharField(choices=[('boundary', 'Boundary Layer'), ('hazard', 'Hazard Layer'), ('infrastructure', 'Infrastructure Layer'), ('custom', 'Custom Layer')], default='custom', max_length=20, verbose_name='Layer Type')),
                ('geojson_data', models.JSONField(help_text='Complete GeoJSON FeatureCollection', verbose_name='GeoJSON Data')),
                ('style_config', models.JSONField(default=dict, help_text='JSON object containing stroke_color, stroke_width, fill_color, fill_opacity, etc.', verbose_name='Style Configuration')),
                ('category_field', models.CharField(blank=True, help_text="Field name in GeoJSON properties for category-based coloring (e.g., 'haz_code')", max_length=100, verbose_name='Category Field Name')),
                ('category_colors', models.JSONField(blank=True, default=dict, help_text="JSON object mapping category values to colors, e.g., {'VHF': '#ff0000', 'HF': '#ff6b00'}", verbose_name='Category Color Mapping')),
                ('is_active', models.BooleanField(default=True, help_text='Show this layer on the map', verbose_name='Active')),
                ('is_visible_default', models.BooleanField(default=True, verbose_name='Visible by Default')),
                ('z_index', models.IntegerField(default=1, help_text='Higher values appear on top', verbose_name='Layer Order (Z-Index)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Map Layer',
                'verbose_name_plural': 'Map Layers',
                'ordering': ['z_index', 'name'],
            },
        ),
    ]
