# Generated by Django 5.2.5 on 2025-12-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_maplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapLayer',
        ),
    ]
