# Generated by Django 5.2.5 on 2025-11-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom Position'),
        ),
    ]
