# Generated by Django 5.2.5 on 2025-11-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_department_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('officer_planning', 'DRRMO OFFICER II PLANNING & RESEARCH'), ('planning_assistant', 'PLANNING ASSISTANT'), ('officer_operation', 'DRRMO OFFICER II OPERATION & WARNING'), ('eoc', 'EMERGENCY OPERATION CENTER'), ('monitoring_alert', 'MONITORING ALERT & WARNING SYSTEM'), ('others', 'Others')], default='others', max_length=50, verbose_name='Position'),
        ),
    ]
