# Generated by Django 5.2.5 on 2025-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_benchmarksettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarksettings',
            name='alert_heavy_rain_threshold',
            field=models.FloatField(default=15, help_text='Daily rainfall threshold to trigger heavy rain alert (mm)'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='alert_total_precipitation_threshold',
            field=models.FloatField(default=50, help_text='Total 7-day precipitation threshold (mm)'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='rainfall_high_threshold',
            field=models.FloatField(default=50, help_text='Rainfall threshold for High Risk (mm)'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='rainfall_moderate_threshold',
            field=models.FloatField(default=30, help_text='Rainfall threshold for Moderate Risk (mm)'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='tide_high_threshold',
            field=models.FloatField(default=1.5, help_text='Tide level threshold for High Risk (m)'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='tide_moderate_threshold',
            field=models.FloatField(default=1.0, help_text='Tide level threshold for Moderate Risk (m)'),
        ),
    ]
