# Generated by Django 5.2.5 on 2025-11-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_benchmarksettings_alert_heavy_rain_threshold_and_more'),
        ('monitoring', '0005_combined_risk_method'),
    ]

    operations = [
    ]
