# Generated by Django 5.2.5 on 2025-11-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_merge_20251119_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmarksettings',
            name='combined_risk_method',
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='rainfall_high_threshold',
            field=models.FloatField(default=50, help_text='Rainfall threshold for High Risk (mm) - High alert when rainfall reaches this level'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='rainfall_moderate_threshold',
            field=models.FloatField(default=30, help_text='Rainfall threshold for Moderate Risk (mm) - Moderate alert when rainfall reaches this level'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='tide_high_threshold',
            field=models.FloatField(default=1.5, help_text='Tide level threshold for High Risk (m) - High alert when tide reaches this level'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='tide_moderate_threshold',
            field=models.FloatField(default=1.0, help_text='Tide level threshold for Moderate Risk (m) - Moderate alert when tide reaches this level'),
        ),
    ]
