# Generated by Django 5.2.5 on 2025-12-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_weatherdata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodrecord',
            name='barangay_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores barangay-level breakdown of all metrics'),
        ),
    ]
