# Generated by Django 5.2.5 on 2025-12-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_floodrecord_barangay_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floodrecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='rainfalldata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='tideleveldata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='rainfalldata',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tideleveldata',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='floodrecord',
            index=models.Index(fields=['-date'], name='monitoring__date_67cf90_idx'),
        ),
        migrations.AddIndex(
            model_name='floodrecord',
            index=models.Index(fields=['event', 'date'], name='monitoring__event_169187_idx'),
        ),
        migrations.AddIndex(
            model_name='rainfalldata',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_e73a67_idx'),
        ),
        migrations.AddIndex(
            model_name='tideleveldata',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_b4df22_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_5b3324_idx'),
        ),
    ]
